#!/usr/bin/env python
from __future__ import with_statement
from __future__ import print_function
from __future__ import division

import os, sys, argparse

from aces_ocio.generate_lut import *


def create(resolution=65):
    # Create a 65 null 3d lut image.

    # Get commandline arguments
    parser = argparse.ArgumentParser(
        description="Create 3 dimensional image for color processing, to create an spi3d lut file."
        )

    parser.add_argument("-o", "--output",
                        type=str,
                        help="output folder",
                        required=False)

    parser.add_argument("--resolution",
                        type=int,
                        help="resolution of ramp",
                        required=False)

    args = parser.parse_args()
    if args.output:
        output = args.output
        output = os.path.expanduser(output)
        output = os.path.realpath(output)
        if not os.path.isdir(output):
            os.makedirs(output)
    else:
        output = os.getcwd()
    if args.resolution:
        resolution = args.resolution

    image_name = "null_3d.{0}.float.tiff".format(resolution)
    output_image = os.path.join(output, image_name)
    print(output_image)

    generate_3d_LUT_image(
        output_image,
        resolution=resolution,
        )


if __name__=="__main__":
    create()